apiVersion: v1
kind: Template
metadata:
  name: 'mysql-generic'
  labels:
    app: mysqldb
objects:
  - kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: '${statefulsetname}'
      labels:
        app: '${statefulsetname}'
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
      triggers:
        - 
          type: ConfigChange
        - 
          type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - '${statefulsetname}'
            from:
              kind: ImageStreamTag
              namespace: '${namespace}'
              name: '${imageName}' 
      replicas: '${replicas}'
      test: false
      selector:
        matchLabels:
          app: '${statefulsetname}'
      template:
        metadata:
          labels:
            app: '${statefulsetname}'
        spec:
          serviceAccountName: mysql-operator
          containers:
            -   
              name: '${statefulsetname}'
              image: '${imageName}' 
              env:
                - 
                  name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                       name: '${secretpassword}'
                       key: password
              ports:
                - containerPort: 3306
                  protocol: TCP
              volumeMounts:
                  - name: mysql-data-dir
                    mountPath: "/var/lib/mysql"
              resources:
                limits:
                  cpu: 1000m
                  memory: 2048Mi
                requests:
                  cpu: 1000m
                  memory: 2048Mi
              imagePullPolicy: Always
            - 
              name: agent
              image: 172.30.1.1:5000/db-mysql-dev/triplea-operator:latest    
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext:
          supplementalGroups:
              - 110
      volumeClaimTemplates:
      - metadata:
          name: mysql-data-dir
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi        
parameters:
  - name: namespace
    displayName: OpenShift namespace
    value: ''
    required: true
  - name: imageName
    displayName: MySQL docker image name
    value: ''
    required: true 
  - name: statefulsetname
    displayName:  MySQL Container statefulset 
    value: ''
    required: true
  - name: replicas
    displayName: number of mysql nodes
    value: ''
    required: true
  - name: secretpassword 
    displayName: a secret that stores root password
    value: ''
    required: true
