apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
  namespace: db-mysql-dev
subjects:
  - kind: ServiceAccount
    name: mysql-operator 
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
