apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: db-mysql-dev 
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["apps"]
    resources:
      - pods
      - pods/exec
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
